# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-20 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_wish_granted'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='likers',
            field=models.ManyToManyField(related_name='liked_wishes', to='main_app.User'),
        ),
    ]
